Fix QuerySet._chain for django main (post-3.2)
jazzband/django-model-utils pull request #495
Opened 2021-08-29 18:43 UTC by tumb1er

## Problem

Tests are failing agains django main branch (post-3.2) because of `QuerySet._chain` signature change:

```
# was
def _chain(self, **kwargs): ...

# now
def _chain(self): ...
```

## Solution

Update additional fields manually

## Commandments

- [x] Write PEP8 compliant code.
- [x] Cover it with tests.
- [ ] Update `CHANGES.rst` file to describe the changes, and quote according issue with `GH-<issue_number>`.
- [x] Pay attention to backward compatibility, or if it breaks it, explain why.
- [ ] Update documentation (if relevant).

2021-08-30 08:06 UTC, auvipy requested changes
this needs unit tests

2021-08-30 08:26 UTC, tumb1er commented
@auvipy  Without that change 36 tests are already failing on django main with:

```
TypeError: _chain() got an unexpected keyword argument 'subclasses'
```

What exactly should be tested?

2021-08-30 08:47 UTC, tumb1er commented
More interesting: if I just delete `_chain` method, no tests are failing. I think that's because `_chain` calls `_clone` internally, and that one does same thing.

2021-10-07 08:51 UTC, MRigal commented on model_utils/managers.py
> +        chained = super()._chain(**kwargs)
Isn't it risky to still pass kwargs here? Sure it should be empty in Django 4+

2021-10-09 10:52 UTC, auvipy approved these changes

2021-10-09 10:52 UTC, merged